{% set name = "lua-compat-5.3-c" %}
{% set version = "0.13" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/lunarmodules/lua-compat-5.3/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f5dc30e7b1fda856ee4d392be457642c1f0c259264a9b9bfbcb680302ce88fc2

build:
  noarch: generic
  number: 0
  script:
    - mkdir -p ${PREFIX}/include/lua-compat-5.3
    - cp -r c-api ${PREFIX}/include/lua-compat-5.3

test:
  commands:
    - test -f ${PREFIX}/include/lua-compat-5.3/c-api/compat-5.3.h
    - test -f ${PREFIX}/include/lua-compat-5.3/c-api/compat-5.3.c

about:
  home: https://github.com/lunarmodules/{{ name }}
  license: MIT
  license_file: LICENSE
  summary: Compatibility module providing Lua-5.3-style APIs for Lua 5.2 and 5.1 (C API only)

extra:
  recipe-maintainers:
    - danielnachun
